name: 'PR Reminders'
description: 'Testing PR Reminders'
author: 'rachelphiliposeRelay'

# Define your inputs here.
inputs:


# Define your outputs here.
outputs:


runs:
  using: node20
  main: dist/index.mjs
