on:
  schedule:
    - cron: '*/7 * * * *'	

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Trigger PR Reminders Step
        id: test
        #- uses: actions/checkout@v3
        #- uses: ./action.yml
        uses: rachelphiliposeRelay/gitbot-test
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        

