on: 
  #schedule:
    #- cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing index.js job!
    steps:
      - name: First step, check out repository
        uses: actions/checkout@v4
        
      - name: Trigger PR Reminders
        id: runs-js-script
        uses: rachelphiliposeRelay/gitbot-test@main
        env:
          REPO_INFO: gitbot-test
          SLACK_CHANNEL_ID: C06MC7JRUBA
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
