on: 
  #schedule:
    #- cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing index.js job!
    steps:
      - name: First step, check out repository
        uses: actions/checkout@v4
        
      - name: Trigger PR Reminders
        id: js script
        uses: rachelphiliposeRelay/gitbot-test@main
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REPO_INFO: ${{ github.repository }}
          SLACK_CHANNEL_ID: C06MC7JRUBA
          