on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing index.js job!
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Trigger PR Reminders Step
        id: test
        uses: ./action.yml
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        

