on:
  schedule:
    - cron: '*/7 * * * *'	

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Trigger PR Reminders Step
        id: test
        uses: rachelphiliposeRelay/gitbot-test-action@v1.1
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        

